### ISSUE TITLE
[AIMBArtHandler _delegateInformDisconnected]  Exception

### ISSUE THREAD

**Issue by eni9889** [unixpickle/LibOrange#4]
Hi,

I posted the following on ChrisBallinger  ChatSecure repo but it seems its a problem with LibOrange

...

I am getting a crash after the app has been running in the background for a 
while and I got to open it. This only happens when one of the accounts that 
I have signed in is an AIM account. 

Here is the crash report: 

http://dl.dropbox.com/u/25626919/ChatSecure%20%2010-3-12%207-49%20PM.crash

**Comment by unixpickle** [comment]
The issue may be related to a glitch in the way the library handles connection failures. I have made a commit to my main LibOrange repository with an insertion that may solve this issue. If it does not, please let me know.

**Comment by eni9889** [comment]
I will give that a try but I found out it only happens after a connection has been ended by peer which happens when an app is brought to the foreground after being in the background for a time that exceeds the allotted time by the system for background processes.

**Comment by unixpickle** [comment]
Yes, this is what I figured. The issue that I fixed was that the following occurred:
- the main OSCAR connection was terminated (died because of backgrounding)
- the session sent a signal to the bart handler which then de-referenced the session
- the BArt OSCAR connection figured out that it died and sent a callback to the BArt handler
- the BArt handler tried to tell the delegate about its problem on the session's main thread (which is nil since the session has been dereferenced)
- an assertion failure occurs because, no duh, the main thread is nil so there's no way code could be running on it

**Comment by eni9889** [comment]
Awesome I figured out it was bc of a niled thread but its great that this is fixed in the latest version. Ill give that a try later on.

**Comment by eni9889** [comment]
Hi,

even after updating to the latest library the error still appears:  **\* Assertion failure in -[AIMBArtHandler _delegateInformDisconnected]"

**Comment by unixpickle** [comment]
I have made another commit to the repo with some additional debugging code. Somewhere in your project, add the following line to enable debugging code. [Debug log:@"-sessionClosed from AIMBArtHandler"];

Next time you get the crash, send me all the debug output so that I can figure out exactly what's going on and fix it.

**Comment by unixpickle** [comment]
Sorry, the correct code is [Debug setDebuggingEnabled:YES];

**Comment by eni9889** [comment]
Here is the crash report I am getting:

http://dl.dropbox.com/u/25626919/ChatSecure%20%2010-9-12%2012-11%20AM.crash

And here is the console output http://pastie.org/5022418

**Comment by unixpickle** [comment]
So it seems that my previous hypothesis was a bit off. As it turns out, the way I queue calls between threads leaves -sessionClosed to be called after -oscarSessionClosed but before -_delegateInformDisconnected. Anyways, I have made a commit that should finally fix the problem. If you still have the issue after this, please bear with me and continue to correspond. It is my responsibility to see that this library is reliable, and I ask for your cooperation as best as you can provide it.

**Comment by eni9889** [comment]
Thank you for all of your support. I'll do some testing and let you know how it goes.

Update: it seems that fixed the issue so I am closing this thread thanks for all of your help
